### ISSUE TITLE
TypeError: 'exc_info' is an invalid keyword argument for print()

### ISSUE THREAD

**Issue by gthelohan** [netinvent/usb_resetter#2]
Hello, I got this message when trying to run usb_resetter.py not as root :

```
Program failed with error Kernel path /sys/kernel/debug/usb/devices not found. Please run this script as root
Traceback (most recent call last):
  File "/home/kali/usb_resetter/usb_resetter/usb_resetter.py", line 430, in main
    interface()
  File "/home/kali/usb_resetter/usb_resetter/usb_resetter.py", line 422, in interface
    get_usb_devices_paths(list_only=True)
  File "/home/kali/usb_resetter/usb_resetter/usb_resetter.py", line 163, in get_usb_devices_paths
    raise OSError(
OSError: Kernel path /sys/kernel/debug/usb/devices not found. Please run this script as root

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/usb_resetter/usb_resetter/usb_resetter.py", line 441, in <module>
    main()
  File "/home/kali/usb_resetter/usb_resetter/usb_resetter.py", line 436, in main
    print("Trace:", exc_info=True)
TypeError: 'exc_info' is an invalid keyword argument for print()
```

It's just the "exc_info" issue... Thanks !

**Comment by deajan** [comment]
Thank you for the catch !
Fixed in https://github.com/netinvent/usb_resetter/commit/d6cc6b1f8776cf2a71fa19182823ccd40c7289ff
